### ISSUE TITLE
Testing: write more tests 🧪🧑🏻‍🔬

### ISSUE THREAD

**Issue by MykalMachon** [TinyboxSoftware/QuickCrypt#3]
## Summary of Issue
Right now, there's really only one, kind of valid test suite. Need to add more. 

## Tasks 
- [ ] Auth tests
- [ ] Better Encryption tests
- [ ] Database tests (maybe?) 
- [ ] UI tests (not sure how to do these given cli)
