### ISSUE TITLE
Feature: copy decrypted password to keyboard 🔑

### ISSUE THREAD

**Issue by MykalMachon** [TinyboxSoftware/QuickCrypt#4]
## Summary
It's probably best that we don't show the password on the terminal.
In most cases, it would be preferable to copy the password to the users clipboard instead. 

## Tasks
- [ ] Find a lib to do this (no native support in Node.js)
- [ ] test on windows
- [ ] test on WSL
- [ ] test on Mac (if possible)
